---
# tasks file for megazord composition
- name: Load var file
  ansible.builtin.include_vars:
    file: main.yml

- name: Run SourcePoint
  ansible.builtin.command: './SourcePoint -Host {{ domain_name }} -Outfile SourcePoint-{{ ansible_date_time.date }}.profile -Injector NtMapViewOfSection -Stage True'
  args:
    chdir: '/tools/SourcePoint'
    creates: '/tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile'

- name: Run cs2modrewrite.py
  ansible.builtin.command: 'python3 cs2modrewrite.py -i /tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile -c https://{{ domain_name }} -r https://{{ redirect_location }} -o .htaccess'
  args:
    chdir: '/tools/cs2modrewrite'
    creates: '/tools/cs2modrewrite/.htaccess'

# Remove the 'P' for proxy because it interferes with the webserver configuration
# Issue described here:
  # https://github.com/hsfetty/ansible-role-megazord-composition/issues/8
- name: Replace instances of 'P' (Proxy)
  ansible.builtin.replace:
    path: /tools/cs2modrewrite/.htaccess
    regexp: '\[P,L]'
    replace: '[L]'

#TODO: Change location and add check for if the file is present
- name: Copy profile into place
  copy:
    src: "{{ default_profile }}"
    dest: "/tools/{{ default_profile }}"
    mode: 0644

#The ansible slurp module will read the file into base64 encoded data
- name: Extract keystore and password from user's profile
  ansible.builtin.slurp:
    src: "/tools/{{ default_profile }}"
  register: encoded_profile

#Decode the encoded profile and split on new line to extract the last 4 lines later
- name: Decode the profile and split on new line
  set_fact:
    https_certificate: "{{ encoded_profile['content'] | b64decode | split('\n') }}"

#Get the last 6 lines of the profile, which contains the https-certificate keystore
#and password, join it to a string, and append it to the SourcePoint profile
- name: Append certificate info to SourcePoint generated profile
  ansible.builtin.blockinfile:
    path: '/tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile'
    block: |
      "{{ https_certificate[-6:] | join('\n') }}"
