---
# tasks file for megazord composition
# - name: Load var file
#   ansible.builtin.include_vars:
#     file: main.yml

- name: Check if profile is already present
  stat:
    path: '/tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile'
  register: stat_profile

#Retry up to 5 times, until status code is 0 (no error)
#Issue documented here:
#https://github.com/hsfetty/ansible-role-megazord-composition/issues/10
- name: Run SourcePoint
  ansible.builtin.command: './SourcePoint -Host {{ domain_name }} -Outfile SourcePoint-{{ ansible_date_time.date }}.profile -Injector NtMapViewOfSection -Stage True'
  args:
    chdir: '/tools/SourcePoint'
    # executable: /bin/bash
  register: sourcepoint_output
  until: sourcepoint_output.rc == 0
  retries: 5
  when: not stat_profile.stat.exists or sourcepoint_output.rc != 0

- name: debug attempts
  debug:
    var: sourcepoint_output.attempts

- name: Run cs2modrewrite.py
  ansible.builtin.command: 'python3 cs2modrewrite.py -i /tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile -c https://{{ domain_name }} -r https://{{ redirect_location }} -o .htaccess'
  args:
    chdir: '/tools/cs2modrewrite'
    creates: '/tools/cs2modrewrite/.htaccess'
    executable: /bin/bash

# Remove the 'P' for proxy because it interferes with the webserver configuration
# Issue described here:
  # https://github.com/hsfetty/ansible-role-megazord-composition/issues/8
- name: Replace instances of 'P' (Proxy)
  ansible.builtin.replace:
    path: /tools/cs2modrewrite/.htaccess
    regexp: '\[P,L]'
    replace: '[L]'
