---
# tasks file for megazord composition
- name: Create the /tools/Megazord-Composition directory
  ansible.builtin.file:
    mode: 0755
    path: /tools/Megazord-Composition
    state: directory

- name: Download and tar the Megazord-Composition
  ansible.builtin.unarchive:
    src: https://github.com/xvxd4sh/megazord-composition/tarball/develop
    dest: /tools/Megazord-Composition
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
    creates: /tools/Megazord-Composition/docker-compose.yml

# pull docker images from dockerhub
- name: Pull docker images used by megazord composition
  block:
    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
    - name: >
        Pull docker images
      community.general.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - xvxd4sh/coredns:latest
        - xvxd4sh/apache2:latest

# Copy service file into correct location and reload services
- name: Configure megazord service
  block:
    #Kali does not have the `docker compose` command because it is using an older version,
    #so it's service file uses `docker-compose`
    - name: Set up megazord as a systemd service (docker compose)
      ansible.builtin.copy:
        src: megazord-composition.service
        dest: /lib/systemd/system/megazord-composition.service
        mode: 0644
      when: not(ansible_distribution == 'Kali')

    - name: Setup service for distros that need docker-compose
      ansible.builtin.copy:
        src: megazord-composition-compose.service
        dest: /lib/systemd/system/megazord-composition.service
        mode: 0644
      when: ansible_distribution == 'Kali'

  when:
    - ansible_service_mgr == "systemd"
