---
# tasks file for megazord composition
- name: Load var file
  ansible.builtin.include_vars:
    file: main.yml

- name: Create the /tools/Megazord-Composition directory
  ansible.builtin.file:
    mode: 0755
    path: /tools/Megazord-Composition
    state: directory

- name: Download and tar the Megazord-Composition
  ansible.builtin.unarchive:
    src: https://github.com/xvxd4sh/megazord-composition/tarball/develop
    dest: /tools/Megazord-Composition
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
    creates: /tools/Megazord-Composition/docker-compose.yml

- name: Run SourcePoint
  ansible.builtin.command: './SourcePoint -Host {{ domain_name }} -Outfile SourcePoint-{{ ansible_date_time.date }}.profile -Injector NtMapViewOfSection -Stage True'
  args:
    chdir: '/tools/SourcePoint'
    creates: '/tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile'
    
- name: Read contents of file
  command: cat SourcePoint-{{ ansible_date_time.date }}.profile
  args:
    chdir: '/tools/SourcePoint'
  changed_when: false
  register: sourcepoint_profile

- name: Debug contents
  debug:
    var: sourcepoint_profile

- name: Make cs2modrewrite good
  ansible.builtin.replace:
    path: /tools/cs2modrewrite/cs2modrewrite.py
    regexp: 'profile = open\(args.inputfile,"r"\)\ncontents = profile.read\(\)'
    replace: 'profile = open(args.inputfile,"r",encoding="utf-8")\ncontents = profile.read().decode("utf-8")'
    
- name: Run cs2modrewrite.py
  ansible.builtin.command: 'python3 cs2modrewrite.py -i /tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile -c https://{{ domain_name }} -r https://{{ redirect_location }} -o /tools/Megazord-Composition/src/apache2/.htaccess'
  args:
    chdir: '/tools/cs2modrewrite'
    creates: '/tools/Megazord-Composition/src/apache2/.htaccess'
  environment: #Environment variables allow older versions of python to read the profile
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    LC_CTYPE: "en_US.UTF-8"

# Remove the 'P' for proxy because it interferes with the webserver configuration
# Issue described here:
  # https://github.com/hsfetty/ansible-role-megazord-composition/issues/8
- name: Replace instances of 'P' (Proxy)
  ansible.builtin.replace:
    path: /tools/Megazord-Composition/src/apache2/.htaccess
    regexp: '\[P,L]'
    replace: '[L]'

#TODO: Change location and add check for if the file is present
- name: Copy profile into place
  copy:
    src: "{{ default_profile }}"
    dest: "/tools/{{ default_profile }}"
    mode: 0644

- name: Extract password
  ansible.builtin.slurp:
    src: "/tools/{{ default_profile }}"
  register: file_data

- name: Append password and keystore to file
  ansible.builtin.blockinfile:
    path: '/tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile'
    block: |
      '{{ file_data["content"] | b64decode }}'
