---
# tasks file for megazord composition
- name: Load var file
  ansible.builtin.include_vars:
    file: main.yml

- name: Attempt to run SourcePoint
  block:
    - name: Run SourcePoint
      ansible.builtin.command: './SourcePoint -Host {{ domain_name }} -Outfile SourcePoint-{{ ansible_date_time.date }}.profile -Injector NtMapViewOfSection -Stage True'
      args:
        chdir: '/tools/SourcePoint'
        creates: '/tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile'
        executable: /bin/bash
  rescue:
    - name: Print error
      ansible.builtin.debug:
        msg: 'Error running SourcePoint. Trying again.'

    - name: Run SourcePoint
      ansible.builtin.command: './SourcePoint -Host {{ domain_name }} -Outfile SourcePoint-{{ ansible_date_time.date }}.profile -Injector NtMapViewOfSection -Stage True'
      args:
        chdir: '/tools/SourcePoint'
        creates: '/tools/SourcePoint/out.profile'
        executable: /bin/bash

- name: Run cs2modrewrite.py
  ansible.builtin.command: 'python3 cs2modrewrite.py -i /tools/SourcePoint/SourcePoint-{{ ansible_date_time.date }}.profile -c https://{{ domain_name }} -r https://{{ redirect_location }} -o .htaccess'
  args:
    chdir: '/tools/cs2modrewrite'
    creates: '/tools/cs2modrewrite/.htaccess'
    executable: /bin/bash

# Remove the 'P' for proxy because it interferes with the webserver configuration
# Issue described here:
  # https://github.com/hsfetty/ansible-role-megazord-composition/issues/8
- name: Replace instances of 'P' (Proxy)
  ansible.builtin.replace:
    path: /tools/cs2modrewrite/.htaccess
    regexp: '\[P,L]'
    replace: '[L]'
