---
# This molecule configuration file is suitable for testing Ansible
# roles that _do_ require SystemD.  If your Ansible role _does not_
# require SystemD then you should use molecule-no-systemd.yml instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
<<<<<<< HEAD
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: geerlingguy/docker-amazonlinux2-ansible:latest
  #   name: amazonlinux2-systemd
  #   platform: amd64
  #   pre_build_image: yes
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
=======
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-amazonlinux2-ansible:latest
    name: amazonlinux2-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
>>>>>>> a1b1d53b93c0ac16106076d12c3de03a77231d51
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-debian10-ansible:latest
    name: debian10-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-debian11-ansible:latest
    name: debian11-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: cisagov/docker-debian12-ansible:latest
    name: debian12-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: cisagov/docker-kali-ansible:latest
    name: kali-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
<<<<<<< HEAD
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: geerlingguy/docker-fedora35-ansible:latest
  #   name: fedora35-systemd
  #   platform: amd64
  #   pre_build_image: yes
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: geerlingguy/docker-fedora36-ansible:latest
  #   name: fedora36-systemd
  #   platform: amd64
  #   pre_build_image: yes
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: geerlingguy/docker-fedora37-ansible:latest
  #   name: fedora37-systemd
  #   platform: amd64
  #   pre_build_image: yes
  #   privileged: yes
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
=======
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora36-ansible:latest
    name: fedora36-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora37-ansible:latest
    name: fedora37-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
>>>>>>> fce8bb34affe56ef03e6ac7feccf733fece5816b
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    name: ubuntu-18-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    name: ubuntu-20-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    name: ubuntu-22-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
<<<<<<< HEAD
provisioner:
  name: ansible
=======
>>>>>>> a1b1d53b93c0ac16106076d12c3de03a77231d51
scenario:
  name: default
verifier:
  name: testinfra
